using System.Collections.Generic;
using FixSourceGenerator.Schema;

namespace FixSourceGenerator.Generators
{
    /// <summary>
    /// Top-level orchestration of the codegen layer: turns a resolved <see cref="FixDictionary"/>
    /// into generated C# source files (runtime helpers, value enums, component readers, and a
    /// reader+writer per message). This is a plain class — the Roslyn <c>IIncrementalGenerator</c>
    /// entry point is wired separately (out of scope for this layer).
    /// </summary>
    public sealed class FixCodeGenerator
    {
        /// <summary>
        /// Generates all source files for <paramref name="schema"/> in <paramref name="namespace"/>.
        /// </summary>
        /// <param name="namespace">The fully resolved base namespace, e.g. <c>Acme.Fix.V44</c>.</param>
        /// <param name="schema">The resolved dictionary model.</param>
        /// <param name="context">Shared bookkeeping and the diagnostic sink.</param>
        public IEnumerable<(string hintName, string content)> Generate(string @namespace, FixDictionary schema, GenerationContext context)
        {
            string runtimeNs = @namespace + ".Runtime";
            string beginString = $"{schema.FixType}.{schema.Major}.{schema.Minor}";

            foreach (var runtime in RuntimeGenerator.Generate(@namespace, context))
            {
                yield return runtime;
            }

            var enumFile = GenerateEnums(@namespace, schema, context);
            if (enumFile != null)
            {
                yield return enumFile.Value;
            }

            foreach (var supportFile in GenerateReaders(@namespace, runtimeNs, schema, context))
            {
                yield return supportFile;
            }

            var readerEmitter = new ReaderEmitter(runtimeNs, context);
            var writerEmitter = new WriterEmitter(runtimeNs);

            foreach (var message in schema.Messages)
            {
                string typeStem = message.Name.ToIdentifier();
                var w = new CodeWriter();
                w.Line("// <auto-generated/>");
                w.Line("#nullable enable");
                w.Open($"namespace {@namespace}");

                readerEmitter.EmitReader(w, typeStem + "Reader", message.Entries);
                w.Line();
                writerEmitter.EmitWriter(w, typeStem + "Writer", message, beginString, schema.Header, schema.Trailer);

                w.Close();
                yield return ($"{@namespace}.{typeStem}.g.cs", w.ToString());
            }
        }

        private static (string hintName, string content)? GenerateEnums(string @namespace, FixDictionary schema, GenerationContext context)
        {
            var enumFields = new Dictionary<string, FixFieldDef>();
            foreach (var message in schema.Messages)
            {
                FixEntryHelpers.CollectEnumFields(message.Entries, enumFields);
            }

            var w = new CodeWriter();
            w.Line("// <auto-generated/>");
            w.Line("#nullable enable");
            w.Open($"namespace {@namespace}");

            bool any = false;
            foreach (var field in enumFields.Values)
            {
                string fullName = @namespace + "." + field.Name.ToIdentifier();
                if (!context.GeneratedEnums.Add(fullName))
                {
                    continue;
                }

                if (any)
                {
                    w.Line();
                }

                EnumGenerator.EmitEnum(w, field);
                any = true;
            }

            w.Close();
            return any ? ($"{@namespace}.Enums.g.cs", w.ToString()) : ((string, string)?)null;
        }

        private static IEnumerable<(string hintName, string content)> GenerateReaders(string @namespace, string runtimeNs, FixDictionary schema, GenerationContext context)
        {
            var components = new Dictionary<string, FixComponentDef>();
            var groups = new Dictionary<string, FixGroupRef>();
            foreach (var message in schema.Messages)
            {
                FixEntryHelpers.CollectComponents(message.Entries, components);
                FixEntryHelpers.CollectGroups(message.Entries, groups);
            }

            var readerEmitter = new ReaderEmitter(runtimeNs, context);

            foreach (var component in components.Values)
            {
                string fullName = @namespace + "." + component.Name.ToIdentifier() + "Reader";
                if (!context.GeneratedComponents.Add(fullName))
                {
                    continue;
                }

                var w = new CodeWriter();
                w.Line("// <auto-generated/>");
                w.Line("#nullable enable");
                w.Open($"namespace {@namespace}");
                readerEmitter.EmitReader(w, component.Name.ToIdentifier() + "Reader", component.Entries);
                w.Close();
                yield return ($"{@namespace}.{component.Name.ToIdentifier()}.g.cs", w.ToString());
            }

            foreach (var group in groups.Values)
            {
                string fullName = @namespace + "." + group.Name.ToIdentifier() + "GroupReader";
                if (!context.GeneratedComponents.Add(fullName))
                {
                    continue;
                }

                var w = new CodeWriter();
                w.Line("// <auto-generated/>");
                w.Line("#nullable enable");
                w.Open($"namespace {@namespace}");
                readerEmitter.EmitStandaloneGroupReader(w, group);
                w.Close();
                yield return ($"{@namespace}.{group.Name.ToIdentifier()}.Group.g.cs", w.ToString());
            }
        }
    }
}
