using System.Collections.Generic;

namespace FixSourceGenerator.Generators
{
    /// <summary>
    /// Emits the shared, allocation-minimal runtime helpers (<c>FixSpanReader</c>,
    /// <c>FixSpanWriter</c>, <c>FixGroupEnumerator</c>) into <c>{ns}.Runtime</c>, once per namespace
    /// (deduped via <see cref="GenerationContext.GeneratedRuntimeNamespaces"/>). The helpers are
    /// embedded as a C# source template, mirroring the SbeSourceGenerator SpanReader/SpanWriter
    /// pattern (docs/CONTRACT.md §2).
    /// </summary>
    internal static class RuntimeGenerator
    {
        public static IEnumerable<(string hintName, string content)> Generate(string @namespace, GenerationContext context)
        {
            if (!context.GeneratedRuntimeNamespaces.Add(@namespace))
            {
                yield break;
            }

            yield return ($"{@namespace}.Runtime.FixRuntime.g.cs", Template.Replace("__NS__", @namespace));
        }

        private const string Template = @"// <auto-generated/>
#nullable enable
using System;
using System.Buffers.Text;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace __NS__.Runtime
{
    /// <summary>
    /// Forward-only, allocation-free scanner over a FIX tag=value byte buffer. Exposes both an
    /// instance forward cursor and static random-access helpers used by generated readers.
    /// </summary>
    public ref struct FixSpanReader
    {
        private const byte Soh = 0x01;

        private readonly ReadOnlySpan<byte> _buffer;
        private int _position;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public FixSpanReader(ReadOnlySpan<byte> buffer)
        {
            _buffer = buffer;
            _position = 0;
        }

        /// <summary>Resets the forward cursor to the start of the buffer.</summary>
        public void Reset() => _position = 0;

        /// <summary>
        /// Advances the forward cursor to the next <c>tag=value</c> field, returning its tag and
        /// value span. Returns false at end of buffer.
        /// </summary>
        public bool TryReadNext(out int tag, out ReadOnlySpan<byte> value)
        {
            if (TryReadField(_buffer, _position, out tag, out int valueStart, out int valueLength, out int nextPos))
            {
                value = _buffer.Slice(valueStart, valueLength);
                _position = nextPos;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Scans the whole buffer for the first occurrence of <paramref name=""tag""/>, returning
        /// its value span without allocating.
        /// </summary>
        public readonly bool TryGetField(int tag, out ReadOnlySpan<byte> value) => TryGetField(_buffer, tag, out value);

        /// <summary>Low-level field parser: reads <c>tag=value&lt;SOH&gt;</c> starting at <paramref name=""pos""/>.</summary>
        public static bool TryReadField(ReadOnlySpan<byte> buffer, int pos, out int tag, out int valueStart, out int valueLength, out int nextPos)
        {
            tag = 0;
            valueStart = 0;
            valueLength = 0;
            nextPos = pos;

            int length = buffer.Length;
            if (pos >= length)
            {
                return false;
            }

            int i = pos;
            int parsedTag = 0;
            bool sawDigit = false;
            while (i < length && buffer[i] != (byte)'=')
            {
                byte c = buffer[i];
                if (c >= (byte)'0' && c <= (byte)'9')
                {
                    parsedTag = (parsedTag * 10) + (c - (byte)'0');
                    sawDigit = true;
                }
                i++;
            }

            if (i >= length || !sawDigit)
            {
                return false;
            }

            i++; // skip '='
            int vStart = i;
            while (i < length && buffer[i] != Soh)
            {
                i++;
            }

            tag = parsedTag;
            valueStart = vStart;
            valueLength = i - vStart;
            nextPos = (i < length) ? i + 1 : i;
            return true;
        }

        public static bool TryGetField(ReadOnlySpan<byte> buffer, int tag, out ReadOnlySpan<byte> value)
        {
            int pos = 0;
            while (TryReadField(buffer, pos, out int t, out int valueStart, out int valueLength, out int nextPos))
            {
                if (t == tag)
                {
                    value = buffer.Slice(valueStart, valueLength);
                    return true;
                }

                pos = nextPos;
            }

            value = default;
            return false;
        }

        public static ReadOnlySpan<byte> GetField(ReadOnlySpan<byte> buffer, int tag)
            => TryGetField(buffer, tag, out var value) ? value : default;

        // --- Pure value-parsing helpers (no tag lookup) -----------------------------------
        // Used by generated readers, which locate each field's (start, length) via a single
        // forward scan in the constructor (docs/CONTRACT.md §2 ""scan único, parse sob
        // demanda""), then parse the already-located span lazily on property access via these
        // helpers. Kept separate from the buffer+tag lookup helpers below (still used e.g. by
        // {Group}GroupReader.Count, which reads a single counter field without needing a full
        // per-entry scan).

        public static bool TryParseInt(ReadOnlySpan<byte> value, out int result)
            => Utf8Parser.TryParse(value, out result, out _);

        public static int ParseInt(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseInt(value, out int result);
            Debug.Assert(ok, ""required INT field is absent or malformed"");
            return result;
        }

        public static bool TryParseDecimal(ReadOnlySpan<byte> value, out decimal result)
            => Utf8Parser.TryParse(value, out result, out _);

        public static decimal ParseDecimal(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseDecimal(value, out decimal result);
            Debug.Assert(ok, ""required decimal field is absent or malformed"");
            return result;
        }

        public static bool TryParseBool(ReadOnlySpan<byte> value, out bool result)
        {
            if (value.Length > 0)
            {
                result = value[0] == (byte)'Y';
                return true;
            }

            result = false;
            return false;
        }

        public static bool ParseBool(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseBool(value, out bool result);
            Debug.Assert(ok, ""required BOOLEAN field is absent or malformed"");
            return result;
        }

        public static bool TryParseByte(ReadOnlySpan<byte> value, out byte result)
        {
            if (value.Length > 0)
            {
                result = value[0];
                return true;
            }

            result = 0;
            return false;
        }

        public static byte ParseByte(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseByte(value, out byte result);
            Debug.Assert(ok, ""required CHAR field is absent or malformed"");
            return result;
        }

        public static bool TryParseDateTime(ReadOnlySpan<byte> value, out DateTime result)
        {
            if (value.Length > 0)
            {
                Span<char> chars = stackalloc char[value.Length];
                for (int i = 0; i < value.Length; i++)
                {
                    chars[i] = (char)value[i];
                }

                return DateTime.TryParseExact(
                    chars,
                    _timestampFormats,
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out result);
            }

            result = default;
            return false;
        }

        public static DateTime ParseDateTime(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseDateTime(value, out DateTime result);
            Debug.Assert(ok, ""required timestamp field is absent or malformed"");
            return result;
        }

        public static bool TryParseDateOnly(ReadOnlySpan<byte> value, out DateOnly result)
        {
            if (value.Length > 0)
            {
                Span<char> chars = stackalloc char[value.Length];
                for (int i = 0; i < value.Length; i++)
                {
                    chars[i] = (char)value[i];
                }

                return DateOnly.TryParseExact(chars, ""yyyyMMdd"", CultureInfo.InvariantCulture, DateTimeStyles.None, out result);
            }

            result = default;
            return false;
        }

        public static DateOnly ParseDateOnly(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseDateOnly(value, out DateOnly result);
            Debug.Assert(ok, ""required date field is absent or malformed"");
            return result;
        }

        public static bool TryParseTimeOnly(ReadOnlySpan<byte> value, out TimeOnly result)
        {
            if (value.Length > 0)
            {
                Span<char> chars = stackalloc char[value.Length];
                for (int i = 0; i < value.Length; i++)
                {
                    chars[i] = (char)value[i];
                }

                return TimeOnly.TryParseExact(chars, _timeFormats, CultureInfo.InvariantCulture, DateTimeStyles.None, out result);
            }

            result = default;
            return false;
        }

        public static TimeOnly ParseTimeOnly(ReadOnlySpan<byte> value)
        {
            bool ok = TryParseTimeOnly(value, out TimeOnly result);
            Debug.Assert(ok, ""required time field is absent or malformed"");
            return result;
        }

        // --- Buffer+tag lookup helpers (single-field scan-from-zero) -----------------------
        // Retained for callers that need to look up one field without materializing a full
        // reader (e.g. {Group}GroupReader.Count, which only ever reads its own counter tag).

        public static bool TryGetInt(ReadOnlySpan<byte> buffer, int tag, out int result)
        {
            if (TryGetField(buffer, tag, out var value) && TryParseInt(value, out result))
            {
                return true;
            }

            result = 0;
            return false;
        }

        public static int GetInt(ReadOnlySpan<byte> buffer, int tag)
        {
            bool ok = TryGetInt(buffer, tag, out int result);
            Debug.Assert(ok, ""required INT field is absent from the buffer"");
            return result;
        }

        /// <summary>
        /// Returns a forward-only, allocation-free enumerator over a space-delimited
        /// MULTIPLEVALUESTRING/MULTIPLECHARVALUE/MULTIPLESTRINGVALUE field (e.g. <c>18=A B C</c>),
        /// splitting on the ASCII space without copying the underlying buffer.
        /// </summary>
        public static FixMultiValueEnumerator GetMultiValue(ReadOnlySpan<byte> buffer, int tag)
        {
            TryGetField(buffer, tag, out var value);
            return new FixMultiValueEnumerator(value);
        }

        private static readonly string[] _timestampFormats =
        {
            ""yyyyMMdd-HH:mm:ss.fff"",
            ""yyyyMMdd-HH:mm:ss"",
        };

        private static readonly string[] _timeFormats =
        {
            ""HH:mm:ss.fff"",
            ""HH:mm:ss"",
        };
    }

    /// <summary>
    /// Forward-only enumerator that slices a repeating-group body into per-entry sub-spans. The
    /// group's counter/delimiter tags and the flattened set of tags that belong to a single entry
    /// are supplied by the generated code (known at compile time — no runtime dictionary lookup),
    /// which is what makes repeating groups allocation-minimal (docs/CONTRACT.md §6).
    /// </summary>
    public ref struct FixGroupEnumerator
    {
        private readonly ReadOnlySpan<byte> _buffer;
        private readonly ReadOnlySpan<int> _entryTags;
        private readonly int _delimiterTag;
        private readonly bool _binarySearch;
        private int _position;
        private int _remaining;
        private ReadOnlySpan<byte> _current;

        public FixGroupEnumerator(ReadOnlySpan<byte> buffer, int counterTag, int delimiterTag, ReadOnlySpan<int> entryTags)
            : this(buffer, counterTag, delimiterTag, entryTags, sortedEntryTags: false)
        {
        }

        internal FixGroupEnumerator(ReadOnlySpan<byte> buffer, int counterTag, int delimiterTag, ReadOnlySpan<int> entryTags, bool sortedEntryTags)
        {
            _buffer = buffer;
            _entryTags = entryTags;
            _delimiterTag = delimiterTag;
            _binarySearch = sortedEntryTags && entryTags.Length > 16;
            _current = default;
            _remaining = 0;
            _position = buffer.Length;

            int pos = 0;
            while (FixSpanReader.TryReadField(buffer, pos, out int tag, out int valueStart, out int valueLength, out int nextPos))
            {
                if (tag == counterTag)
                {
                    FixSpanReader.TryParseInt(buffer.Slice(valueStart, valueLength), out _remaining);
                    _position = nextPos;
                    break;
                }

                pos = nextPos;
            }
        }

        public readonly ReadOnlySpan<byte> Current => _current;

        public bool MoveNext()
        {
            if (_remaining <= 0)
            {
                return false;
            }

            if (!FixSpanReader.TryReadField(_buffer, _position, out int tag, out _, out _, out int afterDelimiter) || tag != _delimiterTag)
            {
                _remaining = 0;
                return false;
            }

            int entryStart = _position;
            int cursor = afterDelimiter;
            while (FixSpanReader.TryReadField(_buffer, cursor, out int nextTag, out _, out _, out int next))
            {
                if (nextTag == _delimiterTag || !Contains(nextTag))
                {
                    break;
                }

                cursor = next;
            }

            _current = _buffer.Slice(entryStart, cursor - entryStart);
            _position = cursor;
            _remaining--;
            return true;
        }

        private readonly bool Contains(int tag)
        {
            var tags = _entryTags;
            if (_binarySearch)
            {
                int low = 0;
                int high = tags.Length - 1;
                while (low <= high)
                {
                    int middle = low + ((high - low) >> 1);
                    int candidate = tags[middle];
                    if (candidate == tag)
                    {
                        return true;
                    }

                    if (candidate < tag)
                    {
                        low = middle + 1;
                    }
                    else
                    {
                        high = middle - 1;
                    }
                }

                return false;
            }

            for (int i = 0; i < tags.Length; i++)
            {
                if (tags[i] == tag)
                {
                    return true;
                }
            }

            return false;
        }
    }

    /// <summary>
    /// Forward-only, allocation-free enumerator over a space-delimited MULTIPLEVALUESTRING /
    /// MULTIPLECHARVALUE / MULTIPLESTRINGVALUE field value, e.g. <c>18=A B C</c>. Each
    /// <see cref=""Current""/> is a sub-span of the original field value — no split/copy into an
    /// array/List (docs/CONTRACT.md §10 ""typed MULTIPLEVALUESTRING/MULTIPLECHARVALUE parsing"").
    /// </summary>
    public ref struct FixMultiValueEnumerator
    {
        private const byte Space = (byte)' ';

        private readonly ReadOnlySpan<byte> _value;
        private int _position;
        private ReadOnlySpan<byte> _current;

        public FixMultiValueEnumerator(ReadOnlySpan<byte> value)
        {
            _value = value;
            _position = 0;
            _current = default;
        }

        public readonly ReadOnlySpan<byte> Current => _current;

        public readonly FixMultiValueEnumerator GetEnumerator() => this;

        public bool MoveNext()
        {
            if (_position > _value.Length)
            {
                return false;
            }

            if (_position == _value.Length)
            {
                if (_position == 0 && _value.Length == 0)
                {
                    // Empty field value: no tokens at all.
                    _position = 1;
                    return false;
                }

                return false;
            }

            int start = _position;
            int end = start;
            while (end < _value.Length && _value[end] != Space)
            {
                end++;
            }

            _current = _value.Slice(start, end - start);
            _position = (end < _value.Length) ? end + 1 : end;
            return true;
        }
    }

    /// <summary>
    /// Allocation-minimal FIX encoder: writes <c>tag=value&lt;SOH&gt;</c> fields directly into a
    /// caller-provided Span of bytes, reserving a fixed-width BodyLength (tag 9)
    /// placeholder that is back-patched, and computing the CheckSum (tag 10) via a running byte sum
    /// on Finish (docs/CONTRACT.md §2.2).
    /// </summary>
    /// <remarks>
    /// Insufficient destination capacity throws ArgumentException and invalidates this instance.
    /// Subsequent writes and Finish throw InvalidOperationException. Partial bytes must be discarded.
    /// Input spans are copied synchronously; only the destination span is retained.
    /// </remarks>
    public ref struct FixSpanWriter
    {
        private const byte Soh = 0x01;
        private const int BodyLengthPlaceholderWidth = 6;

        private Span<byte> _buffer;
        private int _position;
        private int _bodyLengthPos;
        private int _bodyStart;
        private bool _failed;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public FixSpanWriter(Span<byte> buffer)
        {
            _buffer = buffer;
            _position = 0;
            _bodyLengthPos = 0;
            _bodyStart = 0;
            _failed = false;
        }

        public readonly int Position => _position;

        /// <summary>
        /// Writes <c>8=beginString&lt;SOH&gt;</c>, a reserved <c>9=</c> BodyLength placeholder and
        /// <c>35=msgType&lt;SOH&gt;</c>.
        /// </summary>
        public void BeginMessage(scoped ReadOnlySpan<byte> beginString, scoped ReadOnlySpan<byte> msgType)
        {
            WriteField(8, beginString);

            WriteTagPrefix(9);
            EnsureCapacity(BodyLengthPlaceholderWidth + 1);
            _bodyLengthPos = _position;
            for (int i = 0; i < BodyLengthPlaceholderWidth; i++)
            {
                _buffer[_position++] = (byte)'0';
            }

            _buffer[_position++] = Soh;
            _bodyStart = _position;

            WriteField(35, msgType);
        }

        public void WriteField(int tag, scoped ReadOnlySpan<byte> value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, scoped ReadOnlySpan<byte> value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(scoped ReadOnlySpan<byte> value)
        {
            // Compare before adding SOH space so even an int.MaxValue-length input cannot overflow.
            if (value.Length >= _buffer.Length - _position)
            {
                ThrowCapacityExceeded();
            }
            value.CopyTo(_buffer.Slice(_position));
            _position += value.Length;
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, int value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, int value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(int value)
        {
            if (!Utf8Formatter.TryFormat(value, _buffer.Slice(_position), out int written))
            {
                ThrowCapacityExceeded();
            }
            EnsureCapacity(written + 1);
            _position += written;
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, long value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, long value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(long value)
        {
            if (!Utf8Formatter.TryFormat(value, _buffer.Slice(_position), out int written))
            {
                ThrowCapacityExceeded();
            }
            EnsureCapacity(written + 1);
            _position += written;
            _buffer[_position++] = Soh;
        }

        /// <summary>Writes mantissa * 10^-scale, preserving exactly scale fractional digits (0..18).</summary>
        public void WriteField(int tag, long mantissa, int scale)
        {
            ValidateScale(scale);
            WriteTagPrefix(tag);
            WriteValue(mantissa, scale);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, long mantissa, int scale)
        {
            ValidateScale(scale);
            WriteTagPrefix(prefix);
            WriteValue(mantissa, scale);
        }

        private void ValidateScale(int scale)
        {
            ThrowIfFailed();
            if (scale < 0 || scale > 18)
            {
                _failed = true;
                throw new ArgumentOutOfRangeException(nameof(scale), ""Scale must be between 0 and 18."");
            }
        }

        private void WriteValue(long mantissa, int scale)
        {
            Span<byte> digits = stackalloc byte[20];
            if (!Utf8Formatter.TryFormat(mantissa, digits, out int written))
            {
                _failed = true;
                throw new InvalidOperationException(""Mantissa could not be formatted."");
            }

            int signLength = mantissa < 0 ? 1 : 0;
            int digitCount = written - signLength;
            int integerDigits = digitCount - scale;
            int valueLength = signLength + Math.Max(1, integerDigits) + (scale == 0 ? 0 : scale + 1);
            EnsureCapacity(valueLength + 1);

            if (signLength != 0)
            {
                _buffer[_position++] = (byte)'-';
            }
            if (integerDigits > 0)
            {
                digits.Slice(signLength, integerDigits).CopyTo(_buffer.Slice(_position));
                _position += integerDigits;
            }
            else
            {
                _buffer[_position++] = (byte)'0';
            }
            if (scale != 0)
            {
                _buffer[_position++] = (byte)'.';
                int zeroCount = Math.Max(0, -integerDigits);
                _buffer.Slice(_position, zeroCount).Fill((byte)'0');
                _position += zeroCount;
                int fractionStart = signLength + Math.Max(0, integerDigits);
                int fractionLength = written - fractionStart;
                digits.Slice(fractionStart, fractionLength).CopyTo(_buffer.Slice(_position));
                _position += fractionLength;
            }
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, decimal value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, decimal value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(decimal value)
        {
            if (!Utf8Formatter.TryFormat(value, _buffer.Slice(_position), out int written))
            {
                ThrowCapacityExceeded();
            }
            EnsureCapacity(written + 1);
            _position += written;
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, bool value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, bool value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(bool value)
        {
            EnsureCapacity(2);
            _buffer[_position++] = (byte)(value ? 'Y' : 'N');
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, char value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, char value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(char value)
        {
            EnsureCapacity(2);
            _buffer[_position++] = (byte)value;
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, DateTime value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, DateTime value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(DateTime value)
        {
            EnsureCapacity(22);
            // Preserve the supplied clock fields for every Kind, without implicit UTC conversion.
            WriteDate(value.Year, value.Month, value.Day);
            _buffer[_position++] = (byte)'-';
            WriteTime(value.Hour, value.Minute, value.Second, value.Millisecond);
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, DateOnly value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, DateOnly value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(DateOnly value)
        {
            EnsureCapacity(9);
            WriteDate(value.Year, value.Month, value.Day);
            _buffer[_position++] = Soh;
        }

        public void WriteField(int tag, TimeOnly value)
        {
            WriteTagPrefix(tag);
            WriteValue(value);
        }

        internal void WriteField(scoped ReadOnlySpan<byte> prefix, TimeOnly value)
        {
            WriteTagPrefix(prefix);
            WriteValue(value);
        }

        private void WriteValue(TimeOnly value)
        {
            EnsureCapacity(13);
            WriteTime(value.Hour, value.Minute, value.Second, value.Millisecond);
            _buffer[_position++] = Soh;
        }

        private void WriteDate(int year, int month, int day)
        {
            WriteTwoDigits(year / 100);
            WriteTwoDigits(year % 100);
            WriteTwoDigits(month);
            WriteTwoDigits(day);
        }

        private void WriteTime(int hour, int minute, int second, int millisecond)
        {
            WriteTwoDigits(hour);
            _buffer[_position++] = (byte)':';
            WriteTwoDigits(minute);
            _buffer[_position++] = (byte)':';
            WriteTwoDigits(second);
            _buffer[_position++] = (byte)'.';
            _buffer[_position++] = (byte)('0' + millisecond / 100);
            WriteTwoDigits(millisecond % 100);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void WriteTwoDigits(int value)
        {
            _buffer[_position++] = (byte)('0' + value / 10);
            _buffer[_position++] = (byte)('0' + value % 10);
        }

        /// <summary>
        /// Back-patches the BodyLength placeholder to the real body length and appends the
        /// CheckSum field, returning the total number of bytes written.
        /// </summary>
        public int Finish()
        {
            EnsureCapacity(0);
            int bodyLength = _position - _bodyStart;

            Span<byte> digits = stackalloc byte[BodyLengthPlaceholderWidth + 4];
            if (!Utf8Formatter.TryFormat(bodyLength, digits, out int digitCount))
            {
                _failed = true;
                throw new InvalidOperationException(""BodyLength could not be formatted."");
            }

            int delta = digitCount - BodyLengthPlaceholderWidth;
            // Include both the backpatch shift and the complete 10=ddd<SOH> before moving bytes.
            EnsureCapacity(delta + 7);
            if (delta != 0)
            {
                int regionStart = _bodyStart - 1; // the SOH terminating the BodyLength field
                int regionLength = _position - regionStart;
                _buffer.Slice(regionStart, regionLength).CopyTo(_buffer.Slice(regionStart + delta));
                _position += delta;
            }

            digits.Slice(0, digitCount).CopyTo(_buffer.Slice(_bodyLengthPos));

            int sum = 0;
            for (int i = 0; i < _position; i++)
            {
                sum += _buffer[i];
            }

            sum &= 0xFF;

            WriteTagPrefix(10);
            _buffer[_position++] = (byte)('0' + (sum / 100));
            _buffer[_position++] = (byte)('0' + ((sum / 10) % 10));
            _buffer[_position++] = (byte)('0' + (sum % 10));
            _buffer[_position++] = Soh;

            return _position;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void WriteTagPrefix(scoped ReadOnlySpan<byte> prefix)
        {
            EnsureCapacity(prefix.Length);
            prefix.CopyTo(_buffer.Slice(_position));
            _position += prefix.Length;
        }

        private void WriteTagPrefix(int tag)
        {
            EnsureCapacity(1);
            if (!Utf8Formatter.TryFormat(tag, _buffer.Slice(_position), out int written))
            {
                ThrowCapacityExceeded();
            }
            EnsureCapacity(written + 1);
            _position += written;
            _buffer[_position++] = (byte)'=';
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private readonly void ThrowIfFailed()
        {
            if (_failed)
            {
                throw new InvalidOperationException(""The writer is invalid after a failed operation. Create a new writer."");
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void EnsureCapacity(int required)
        {
            ThrowIfFailed();
            if (required > _buffer.Length - _position)
            {
                ThrowCapacityExceeded();
            }
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private void ThrowCapacityExceeded()
        {
            _failed = true;
            throw new ArgumentException(""The destination buffer is too small."", ""destination"");
        }
    }
}
";
    }
}
