<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <FixGeneratorNamespace>Compatibility</FixGeneratorNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FixSourceGenerator/FixSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="../FixSourceGenerator.Tests/TestData/FIX44.xml" />
    <CompilerVisibleProperty Include="FixGeneratorNamespace" />
    <Compile Include="../FixSourceGenerator.Tests/ScopedApiContractExamples.cs" Link="ScopedApiContractExamples.cs" />
  </ItemGroup>
</Project>
