namespace FixSourceGenerator.Views
{
    /// <summary>
    /// Source template for the <c>[FixView]</c>/<c>[FixField]</c> attributes emitted once per
    /// compilation via <c>RegisterPostInitializationOutput</c> (issue #13, docs/CONTRACT.md §11).
    /// </summary>
    /// <remarks>
    /// Consumers reference these from <c>FixSourceGenerator.Attributes</c> (per the issue's
    /// acceptance criteria) to annotate a hand-written <c>partial struct</c> with the subset of
    /// fields they're interested in, without depending on the full generated message reader.
    /// <para>
    /// Note: using <c>[FixView]</c> requires the consumer's partial-property members to compile,
    /// which needs C# 13 / a net9+-era SDK (LangVersion Preview/13+, per Roslyn 4.11). This is
    /// stricter than the rest of the generator (readers/writers only require net6+); the rest of
    /// the generator is unaffected since it never emits partial properties.
    /// </para>
    /// </remarks>
    internal static class FixViewAttributes
    {
        public const string HintName = "FixSourceGenerator.Attributes.FixViewAttributes.g.cs";

        public const string AttributeNamespace = "FixSourceGenerator.Attributes";

        public const string FixViewAttributeMetadataName = "FixSourceGenerator.Attributes.FixViewAttribute";

        public const string FixFieldAttributeMetadataName = "FixSourceGenerator.Attributes.FixFieldAttribute";

        public const string Source = @"// <auto-generated/>
#nullable enable
namespace FixSourceGenerator.Attributes
{
    /// <summary>
    /// Marks a <c>partial struct</c> as a selective projection ('view') over the fields of a
    /// single FIX message. The generator matches each <c>partial</c> property declared on the
    /// struct against the named message's fields (by property name, or by an explicit
    /// <see cref=""FixFieldAttribute""/> override) and emits a single forward-only, early-exit
    /// scanning constructor plus the missing property bodies.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class FixViewAttribute : System.Attribute
    {
        public FixViewAttribute(string messageName)
        {
            MessageName = messageName;
        }

        /// <summary>The target message's &lt;message name=""...""&gt; from the loaded schema.</summary>
        public string MessageName { get; }
    }

    /// <summary>
    /// Overrides the field a <c>[FixView]</c> property is matched against, for when the property
    /// name diverges from the schema field name.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class FixFieldAttribute : System.Attribute
    {
        public FixFieldAttribute(string fieldName)
        {
            FieldName = fieldName;
        }

        /// <summary>The &lt;field name=""...""&gt; this property should be matched against.</summary>
        public string FieldName { get; }
    }
}
";
    }
}
