using System;
using System.Collections.Generic;
using FixSourceGenerator.Generators;
using FixSourceGenerator.Schema;

namespace FixSourceGenerator.Views
{
    /// <summary>
    /// Shares group-boundary helpers between views in the same runtime namespace.
    /// Definition identity distinguishes homonymous groups and independently parsed schemas.
    /// </summary>
    /// <remarks>
    /// <see cref="FixGroupRef"/> uses reference equality. Mutable ids stay local to one output batch.
    /// </remarks>
    internal sealed class GroupHelperRegistry
    {
        public const string ContainerTypeName = "FixViewGroupSkipHelpers";

        private sealed class SchemaState
        {
            public readonly Dictionary<FixGroupRef, string> Ids = new Dictionary<FixGroupRef, string>();
            public readonly HashSet<FixGroupRef> Emitted = new HashSet<FixGroupRef>();
            public readonly CodeWriter Body = new CodeWriter();
        }

        private readonly Dictionary<string, SchemaState> _bySchema = new Dictionary<string, SchemaState>(StringComparer.Ordinal);

        /// <summary>
        /// Assigns batch-local ids and emits each reachable group's body once.
        /// </summary>
        public Dictionary<FixGroupRef, string> EnsureHelpers(string runtimeNs, IReadOnlyList<FixGroupRef> directGroups)
        {
            if (!_bySchema.TryGetValue(runtimeNs, out var state))
            {
                state = new SchemaState();
                _bySchema[runtimeNs] = state;
            }

            GroupScopeEmitter.AssignIds(directGroups, state.Ids);
            foreach (var group in directGroups)
            {
                GroupScopeEmitter.EmitSkipHelper(state.Body, runtimeNs, group, state.Ids, state.Emitted);
            }

            return state.Ids;
        }

        /// <summary>
        /// Uses the runtime namespace to avoid type and hint-name collisions with FIX definitions.
        /// </summary>
        public IEnumerable<(string HintName, string Content)> BuildOutputs()
        {
            foreach (var pair in _bySchema)
            {
                string runtimeNs = pair.Key;
                SchemaState state = pair.Value;
                if (state.Emitted.Count == 0)
                {
                    continue;
                }

                var w = new CodeWriter();
                w.Line("// <auto-generated/>");
                w.Line("#nullable enable");
                w.Line();
                w.Open($"namespace {runtimeNs}");
                w.Line("/// <summary>");
                w.Line("/// Shared group-boundary skip helpers for every [FixView] projection over this");
                w.Line("/// schema (issue #32): one method per distinct group topology, reused by every view");
                w.Line("/// that needs to skip past it instead of each view re-emitting its own copy.");
                w.Line("/// </summary>");
                w.Open($"internal static class {ContainerTypeName}");
                AppendBody(w, state.Body.ToString());
                w.Close();
                w.Close();

                yield return ($"{runtimeNs}.{ContainerTypeName}.g.cs", w.ToString());
            }
        }

        /// <summary>
        /// Re-indents a rendered block inside the namespace and container.
        /// </summary>
        private static void AppendBody(CodeWriter w, string body)
        {
            foreach (var line in body.Split('\n'))
            {
                string trimmed = line.TrimEnd('\r');
                if (trimmed.Length == 0)
                {
                    w.Line();
                }
                else
                {
                    w.Line(trimmed);
                }
            }
        }
    }
}
