name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
      - name: Restore
        run: dotnet restore FixSourceGenerator.sln
      - name: Build
        run: dotnet build FixSourceGenerator.sln --no-restore -c Release
      - name: Test
        run: dotnet test FixSourceGenerator.sln --no-build -c Release
